### ISSUE TITLE
Password on zip file for Win64

### ISSUE THREAD

**Issue by Flow-Live** [216k155/sgminer-phi1612-Implemented#1]
Password on zip file for Win64

**Comment by patwinxyz** [comment]
what is the PASSWORD?

**Comment by Flow-Live** [comment]
That is my question!

**Comment by stanleybg** [comment]
It finds very danger virus in miner.

**Comment by KOMODOBEAST** [comment]
Password please

**Comment by yl519603193** [comment]
Password please

**Comment by laugh26** [comment]
password for the linux

**Comment by laugh26** [comment]
nice job from you guys

**Comment by laugh26** [comment]
for the sgminer

**Comment by MrSeree** [comment]
The password file was the only un-encrypted file in the zip... password: elbandiminer
