### ISSUE TITLE
Core clock unstable beyond 1.2Ghz on RX580

### ISSUE THREAD

**Issue by nicokapo34** [216k155/sgminer-phi1612-Implemented#3]
I have been using this miner for quite a while, and I noticed some weird performance with my RX580: whenever you apply +1200Mhz or more on the core clock, it doesn't get applied properly, and the clock just starts rising and falling quite quickly (+-75/100Mhz). I don't have this problem with other miners: that's how I know the issue must be related to this one. The bigger problem: if I try to apply a 1360Mhz core clock, it will just stay at 1270 +- 75Mhz.

Also, VDDC is quite erratic.

![image](https://user-images.githubusercontent.com/8285192/33811817-2b357e54-ddf6-11e7-957f-f5731e3066bd.png)

Thank you.

**Comment by anorganix** [comment]
Every algo and card has its specifics. Probably +1200 or more is not suited for your card on this algo.
